name: publish project-cli
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: install
        run: yarn
      - name: set user meta
        run: |
          git config --global user.name mengshang918
          git config --global user.email 1446269124@qq.com
      - name: lerna version
        run: yarn lerna version --yes --conventional-commits
      - name: lerna publish
        run: yarn lerna publish from-package --yes --no-verify-access
